#@ load("@ytt:data", "data")
#@ load("@ytt:base64", "base64")
apiVersion: v1
kind: Secret
metadata:
  name: common-secrets
  namespace: concourse-main
type: Opaque
data:
  harborDomain: #@ base64.encode(data.values.commonSecrets.harborDomain)
  harborUser: #@ base64.encode(data.values.commonSecrets.harborUser)
  harborPassword: #@ base64.encode(data.values.commonSecrets.harborPassword)
  kubeconfigBuildServer: #@ base64.encode(data.values.commonSecrets.kubeconfigBuildServer)
  kubeconfigDeployServer: #@ base64.encode(data.values.commonSecrets.kubeconfigAppServer)
  kubernetesBuildServiceAccountToken: #@ base64.encode(data.values.commonSecrets.kubernetesBuildServiceAccountToken)
  kubernetesDeployServiceAccountToken: #@ base64.encode(data.values.commonSecrets.kubernetesDeployServiceAccountToken)
  kubernetesDeployCluster: #@ base64.encode(data.values.commonSecrets.kubernetesDeployCluster)
  kubernetesBuildCluster: #@ base64.encode(data.values.commonSecrets.kubernetesBuildCluster)
  concourseHelperImage: #@ base64.encode(data.values.commonSecrets.concourseHelperImage)
  pivnetApiToken: #@ base64.encode(data.values.commonSecrets.pivnetApiToken)
---  
apiVersion: v1
kind: Secret
metadata:
  name: tanzu-edge-pos-service
  namespace: concourse-main
type: Opaque
data:
  host: #@ base64.encode(data.values.app.host)
  image: #@ base64.encode(data.values.app.image)
  tbsNamespace: #@ base64.encode(data.values.app.tbs.namespace)
  wavefrontApplicationName: #@ base64.encode(data.values.app.wavefront.applicationName)
  wavefrontUri: #@ base64.encode(data.values.app.wavefront.uri)
  wavefrontApiToken: #@ base64.encode(data.values.app.wavefront.apiToken)
  wavefrontDeployEventName: #@ base64.encode(data.values.app.wavefront.deployEventName)
  configRepo: #@ base64.encode(data.values.app.configRepo)
  codeRepo: #@ base64.encode(data.values.app.codeRepo)
  serverless: #@ base64.encode(data.values.app.serverless)
  profile: #@ base64.encode(data.values.app.profile)
