spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/tanzu-pos"
    username: tanzu
    password: tanzu
  rabbitmq:
    username: user
    password: bitnami
 
wavefront:
  freemium-account: false
  application:
    name: pos-txn-receiver
    service: POS

management:
  metrics: 
    export:
      wavefront:
        uri: proxy://192.168.0.5:2878
        