spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: "jdbc:postgresql://localhost:5432/tanzu-pos"
    username: tanzu
    password: tanzu
  rabbitmq:
    username: user
    password: bitnami
  sleuth:
    baggage:
      remoteFields:
        - storeId
        - x-vcap-request-id
      tagFields:
        - storeId
    traceId128: true
    propagation-keys: storeId
logging:
  pattern:
    level: "[%X{traceId}/%X{spanId}] %-5p [%t] %C{2} - %m%n"
 
wavefront:
  freemium-account: false
  application:
    name: edge-pos-txn-receiver
    service: Tanzu-Edge-Store

management:
  metrics: 
    export:
      wavefront:
        uri: proxy://192.168.0.5:2878
        