spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
  
pos:
 storeId: localTEST
 
wavefront:
  application:
    name: edge-pos-txn-sender

rabbitmq:
  host: localhost
  virtualHost: in-store-vhost
