kind: ConfigMap
apiVersion: v1
metadata:
  name: pos-receiver-config
data:
  SPRING_PROFILES_ACTIVE: receiver
  SPRING_RABBITMQ_HOST: tanzu-messaging-dc-rabbitmq.datacenter-database.svc.cluster.local
  SPRING_RABBITMQ_PASSWORD: jaHiKxZ5KZ 
  SPRING_DATASOURCE_USERNAME: tanzu
  SPRING_DATASOURCE_PASSWORD: tanzu
  SPRING_DATASOURCE_URL: "jdbc:postgresql://tanzu-database.datacenter-database.svc.cluster.local:5432/tanzu-po"
